config/routes.rb
Apps4ottawa::Application.routes.draw do

  scope "/(:locale)", :constraints => {:locale => /en|fr/} do
    devise_for :users

    resources :idea_comments
    resources :app_comments

    resources :ideas do
      member do
        put :like
      end
    end

    resources :apps do
      member do
        put :like
      end
    end

    resources :about do
      collection do
        get :index
        get :faq
        get :rules
        get :terms
        get :privacy
      end
    end

    root :to => 'main#index'
  end

end

app/views/shared/_about_menu.html.erb
<ul class="subnav">
  <li<%= (current_page?(:action => 'index') ? ' class="current"' : "").html_safe %>>
    <%= link_to t(:about), "#{about_index_path}#summary", :class => 'subnav-item' %>
    
    <ul class="subsubnav">
      <li><%= link_to t(:important_dates), "#{about_index_path}#dates", :class => 'subnav-item' %></li>
      <li><%= link_to t(:categories), "#{about_index_path}#categories", :class => 'subnav-item' %></li>
      <li><%= link_to t(:prizes), "#{about_index_path}#prizes", :class => 'subnav-item' %></li>
      <li><%= link_to t(:judges), "#{about_index_path}#judges", :class => 'subnav-item' %></li>
    </ul>
  </li>
  <li<%= (current_page?(:action => 'faq') ? ' class="current"' : "").html_safe %>>
    <%= link_to t(:faq), faq_about_index_path, :class => "subnav-item" %>
  </li>
  <li<%= (current_page?(:action => 'rules') ? ' class="current"' : "").html_safe %>>
    <%= link_to t(:rules), rules_about_index_path, :class => "subnav-item" %>
  </li>
  <li<%= (current_page?(:action => 'terms') ? ' class="current"' : "").html_safe %>>
    <%= link_to t(:terms), terms_about_index_path, :class => "subnav-item" %>
  </li>
  <li<%= (current_page?(:action => 'privacy') ? ' class="current"' : "").html_safe %>>
    <%= link_to t(:privacy), privacy_about_index_path, :class => "subnav-item" %>
  </li>
</ul>

app/views/shared/_app_card.html.erb
<li class="hentry">
  <% unless app.screenshot_file_name.nil? %>
  <a href="/<%= I18n.locale %>/apps/<%=h app.id %>" class="hentry-item has-screenshot" target="_blank" style="background-image:url('<%=h app.screenshot.url(:thumb) %>')">
  <% else %>
  <a href="/<%= I18n.locale %>/apps/<%=h app.id %>" target="_blank" class="hentry-item">
  <% end %>
    <span class="hentry-wrapper">
      <strong class="entry-title"><%=h app.name %></strong>
      <span class="author"><%=h app.user.name %></span>
      <span class="desc"><%=h snippet(app.description, 20) %></span>
      <span class="comments" title="<%=h app.app_comments.size %> <%=h (app.app_comments.size != 1) ? t(:commented_app_plural) : t(:commented_app) %>"><%=h app.app_comments.size %></span>
      <span class="likes" title="<%=h app.rating %> <%=h (app.rating != 1) ? t(:voted_app_plural) : t(:voted_app) %>"><%=h app.rating %></span>
    </span>
  </a>
  <% if current_user && (app.user == current_user || current_user.admin?) %>
    <div class="user-tools">
      <a href="/<%= I18n.locale %>/apps/<%=h app.id %>/edit" class="edit"><%=t :edit %></a> · 
      <%= form_for(app, :url => { :controller => 'apps', :action => 'destroy', :locale => I18n.locale, :id => app.id }, :html => { :class => 'inline', :method => 'delete' }) do |f| %>
        <button type="submit" class="btn-simple delete"><%=t :delete %></button>
      <% end %>
    </div>
  <% end %>
</li>

app/views/shared/_apps_banner.html.erb
<div class="secondary intro-box action apps-callout">
	<div class="intro-box-wrapper clearfix">
	<% if Apps4ottawa::Application::ALLOW_APP_SUBMISSION == true %>
		<p class="desc"><%=t :intro_apps %></p>
		<a href="/<%= I18n.locale %>/apps/new" class="btn btn-alt"><%=t :intro_apps_button %></a>
	<% else %>
		<p class="desc"><%=t :intro_apps %></p>
	<% end %>
	</div>
</div>
<div class="primary apps-summary">
	<h1 id="summary"><%=t :apps_heading %></h1>
	<p><%=t :apps_blurb %></p>
</div>

app/views/shared/_categories.html.erb
<ul>
  <li><%=t :category_fun %></li>
  <li><%=t :category_around %></li>
  <li><%=t :category_green %></li>
  <li><%=t :category_community %></li>
  <li><%=t :category_economic %></li>
</ul>

app/views/shared/_dates.html.erb
<dl>
	<dt><%=t :compeititon_date_title %></dt>
	<dd><%=t :compeititon_date %></dd>
	<dt><%=t :public_date_title %></dt>
	<dd><%=t :public_date %></dd>
	<dt><%=t :judging_date_title %></dt>
	<dd><%=t :judging_date %></dd>
	<dt><%=t :awards_date_title %></dt>
	<dd><%=t :awards_date %></dd>
</dl>

app/views/shared/_idea_card.html.erb
<li class="hentry">
  <a href="/<%= I18n.locale %>/ideas/<%=h idea.id %>" target="_blank" class="hentry-item">
    <strong class="entry-title"><%=h idea.name %></strong>
    <span class="author"><%=h idea.user.name %></span>
    <span class="desc"><%=h snippet(idea.description, 20) %></span>
    <span class="comments" title="<%=h idea.idea_comments.size %> <%=h (idea.idea_comments.size != 1) ? I18n.t(:commented_idea_plural) : I18n.t(:commented_idea) %>"><%=h idea.idea_comments.size %></span>
    <span class="likes" title="<%=h idea.rating %> <%=h (idea.rating != 1) ? I18n.t(:voted_idea_plural) : I18n.t(:voted_idea) %>"><%=h idea.rating %></span>
  </a>
  <% if current_user && (idea.user == current_user || current_user.admin?) %>
    <div class="user-tools">
      <a href="/<%= I18n.locale %>/ideas/<%=h idea.id %>/edit" class="edit"><%=t :edit %></a> · 
      <%= form_for(idea, :url => { :controller => 'ideas', :action => 'destroy', :locale => I18n.locale, :id => idea.id }, :html => { :class => 'inline', :method => 'delete' }) do |f| %>
        <button type="submit" class="btn-simple delete"><%=t :delete %></button>
      <% end %>
    </div>
  <% end %>
</li>

app/views/shared/_ideas_banner.html.erb
<div class="secondary intro-box action">
	<div class="intro-box-wrapper clearfix">
	<% if Apps4ottawa::Application::ALLOW_IDEA_SUBMISSION == true %>
		<p class="desc"><%=t :intro_ideas %></p>
		<a href="/<%= I18n.locale %>/ideas/new" class="btn btn-alt"><%=t :intro_ideas_button %></a>
	<% else%>
		<p class="desc"><%=t :intro_ideas %></p>
	<% end %>
	</div>
</div>
<div class="primary">
	<h1 id="summary"><%=t :ideas_heading %></h1>
	<p><%=t :ideas_blurb %></p>
</div>

app/views/shared/_wrapper_bottom.html.erb
<footer class="foot" role="contentinfo">
  <p>© 2010 <%=t :city_ottawa %> · <a href="/<%= I18n.locale %>/about/privacy"><%=t :privacy %></a> · <a href="/<%= I18n.locale %>/about/terms"><%=t :terms %></a> · <a href="/<%= I18n.locale %>/about/rules"><%=t :rules %></a></p>
</footer>
<%= javascript_include_tag :defaults, 'jquery.tweet.js' %>
<script type="text/javascript">
  var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
  document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
</body>
</html>

app/views/shared/_wrapper_top.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>" class="<%= I18n.locale %>">
<head>
  <meta charset="utf-8">
  <title><%= (title = yield(:title)).present? ? title : t(:home_title) %></title>
  <meta name="ICBM" content="45.3333333,-75.5841666">
  <meta name="geo.position" content="45.3333333,-75.5841666">
  <meta name="geo.placename" content="Ottawa, Ontario, Canada">
  <meta name="geo.region" content="ca-on">
  <meta name="viewport" content="width=1100">
  <%= javascript_include_tag 'modernizr-1.5.min.js' %>
  <%= stylesheet_link_tag 'desktop', :media => "screen,projection,tv" %>
  <link rel="profile" href="http://microformats.org/profile/hatom">
  <link rel="shortcut icon" href="/favicon.ico">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">
  <%= csrf_meta_tag %>
</head>
<!--[if lt IE 7 ]><body role="document" class="ie6"><![endif]-->
<!--[if IE 7 ]><body role="document" class="ie7"><![endif]-->
<!--[if IE 8 ]><body role="document" class="ie8"><![endif]-->
<!--[if IE 9 ]><body role="document" class="ie9"><![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--><body role="document"><!--<![endif]-->

<header role="banner" class="masthead clearfix">
  <div class="masthead-wrapper">
    <div class="user-info">
    <% if current_user %>
      <p class="user"><%= current_user.email %> · 
        <%= link_to t(:'devise.labels.profile'), edit_user_registration_path %> · <%= link_to t(:'devise.common.sign_out'), destroy_user_session_path %>
      </p>
    <% else %>
      <p class="user">
        <%= link_to t(:'devise.registrations.link'), new_user_registration_path %> · <%= link_to t(:'devise.common.sign_in'), new_user_session_path %></p>
    <% end %>
    </div>

    <nav class="nav-tools">
      <ul class="nav-group clearfix">
        <li class="nav-item ottawa" title="<%=t :city_ottawa %>"><a href="http://ottawa.ca/index_<%= I18n.locale %>.html" rel="external" class="nav-item-inner"><span class="nav-label"><%=t :city_ottawa %></span></a></li>
        <li class="nav-item lang">
          <%= link_to url_for(:locale => t(:other_locale)), :class => "nav-item-inner", :lang => t(:other_locale), :hreflang => t(:other_locale) do %>
            <span class="nav-label"><%= t :other_language %></span>
          <% end %>
        </li>
      </ul>
    </nav>

    <nav class="nav" role="navigation">
      <ul class="nav-group clearfix">
        <li class="nav-item about<%= controller.controller_name == 'about' ? " current" : "" %>">
          <%= link_to about_index_path, :class => "nav-item-inner" do %>
            <span class="nav-label"><%=t :about %></span>
          <% end %>
        </li>
        <li class="nav-item data"><a href="http://www.ottawa.ca/online_services/opendata/index_<%= I18n.locale %>.html" class="nav-item-inner" rel="external"><span class="nav-label"><%=t :data %></span></a></li>

        <li class="nav-item home" title="<%=t :home %>">
          <%= link_to root_url, :class => "nav-item-inner" do %>
            <span class="nav-label"><%=t :home %></span>
          <% end %>
        </li>

        <li class="nav-item ideas<%= controller.controller_name == 'ideas' ? " current" : "" %>">
          <%= link_to ideas_path, :class => "nav-item-inner" do %>
            <span class="nav-label"><%=t :ideas %></span>
          <% end %>
        </li>

        <li class="nav-item apps<%= controller.controller_name == 'apps' ? " current" : "" %>">
          <%= link_to apps_path, :class => "nav-item-inner" do %>
            <span class="nav-label"><%=t :apps %></span>
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
</header>